name: solidcalculator
base: core18 
version: '2.0' 
summary: A Simple Solid Calculator for Linux 
description: |
  A Simple Solid Calculator for Linux

grade: stable 
confinement: strict 

parts:
  my-part:
    plugin: nil
